# Generated by Django 6.0.3 on 2026-03-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='slug',
            field=models.SlugField(max_length=200, unique_for_date='created'),
        ),
    ]
