# Generated by Django 6.0.3 on 2026-03-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_alter_config_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='image',
            field=models.ImageField(default='exit', upload_to='images/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
