# Generated by Django 6.0.3 on 2026-03-12 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0003_config_image_delete_image'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='config',
            managers=[
            ],
        ),
        migrations.AddConstraint(
            model_name='config',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='unique_slug_per_user'),
        ),
    ]
